### ISSUE TITLE
Empty logger message in every run

### ISSUE THREAD

**Issue by JaroslavTrsek** [neurobin/phantomjspy#4]
Hi,

I probably found the error in [phantomjs/phantom.py#L38](https://github.com/neurobin/phantomjspy/blob/dbd6d24cf5ff7a2d3c3a7b77dd850e46ab3fe6d4/phantomjs/phantom.py#L38). This generates lots of unuseful entries (level error) in my log. It happens even if I run [example from readme](https://github.com/neurobin/phantomjspy#using-with-a-custom-phantomjs-script).

It would be possible to change this code to something like this?

```
if errors:
    self.logger.error(errors)
```

**Comment by neurobin** [comment]
sure, you can make a pull request.
